/*
  data.js
  -------
  SINGLE RESPONSIBILITY: Be the data layer.
  This file does ONE thing — it holds the data.
  No rendering. No logic. No DOM touching.

  WHY A CONST ARRAY AT THE TOP LEVEL?
  Because it lives on the window object (global scope),
  every other JS file loaded after this one can read RECIPES.
  This is our deliberate, controlled use of global scope.

  FUTURE SWAP: When you integrate the Spoonacular API,
  you'll replace this array with an async fetch call.
  Nothing else in the codebase changes — only this file.

  SHAPE CONSISTENCY: Every object has the exact same keys.
  If you add a recipe, it must have ALL these keys.
  Missing keys cause silent bugs in the render functions.
*/

const RECIPES = [
  {
    id: 1,
    title: "Greek Buddha Bowl",
    description:
      "A vibrant medley of roasted chickpeas, tzatziki, cucumber, olives, and feta over herbed quinoa.",
    image:
      "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&q=80",
    time: "25 min",
    prepTime: 25,
    calories: "420 kcal",
    servings: 2,
    rating: 4.8,
    badge: "🔥 Trending",
    category: "vegan",
    cuisine: 'Mediterranean',
    diet: ["vegan", "vegetarian", "gluten-free"],
    tags: ["Vegan", "Gluten-Free"],
    difficulty: "easy",
  },
  {
    id: 2,
    title: "Truffle Pasta Carbonara",
    description:
      "Classic Roman carbonara elevated with shaved black truffle and aged Pecorino Romano.",
    image:
      "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=500&q=80",
    time: "20 min",
    prepTime: 20,
    calories: "680 kcal",
    servings: 2,
    rating: 4.9,
    badge: "⭐ Top Rated",
    category: "comfort",
    cuisine: "italian",
    diet: [],
    tags: ["Italian", "Indulgent"],
    difficulty: "medium",
  },
  {
    id: 3,
    title: "Mango Coconut Chia Pudding",
    description:
      "Creamy overnight chia pudding layered with fresh mango salsa and toasted coconut flakes.",
    image:
      "https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?w=500&q=80",
    time: "10 min",
    prepTime: 10,
    calories: "280 kcal",
    servings: 1,
    rating: 4.7,
    badge: "Quick",
    category: "breakfast",
    cuisine: "asian",
    diet: ["vegan", "vegetarian", "gluten-free", "dairy-free"],
    tags: ["Vegan", "Quick"],
    difficulty: "easy",
  },
  {
    id: 4,
    title: "Spiced Lamb Kofta",
    description:
      "Juicy lamb kofta skewers seasoned with cumin, coriander and fresh herbs, served with tahini.",
    image:
      "https://images.unsplash.com/photo-1529042410759-befb1204b468?w=500&q=80",
    time: "35 min",
    prepTime: 35,
    calories: "510 kcal",
    servings: 4,
    rating: 4.6,
    badge: "High-Protein",
    category: "high-protein",
    cuisine: "middle-eastern",
    diet: ["gluten-free"],
    tags: ["High-Protein", "Grilled"],
    difficulty: "medium",
  },
  {
    id: 5,
    title: "Avocado Toast Three Ways",
    description:
      "Three gorgeous takes on avocado toast: classic, spicy kimchi, and everything bagel style.",
    image:
      "https://images.unsplash.com/photo-1541519227354-08fa5d50c820?w=500&q=80",
    time: "12 min",
    prepTime: 12,
    calories: "340 kcal",
    servings: 1,
    rating: 4.5,
    badge: "⚡ Quick",
    category: "quick",
    cuisine: 'american',
    diet: ["vegetarian", "dairy-free"],
    tags: ["Quick", "Vegetarian"],
    difficulty: "easy",
  },
  {
    id: 6,
    title: "Baklava Cheesecake",
    description:
      "A marriage of creamy vanilla cheesecake and flaky honey-walnut baklava on a buttery pastry base.",
    image:
      "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=500&q=80",
    time: "90 min",
    prepTime: 90,
    calories: "520 kcal",
    servings: 12,
    rating: 4.9,
    badge: "Chef's Pick",
    category: "dessert",
    cuisine: "middle-eastern",
    diet: ["vegetarian"],
    tags: ["Dessert", "Baked"],
    difficulty: "hard",
  },
  {
    id: 7,
    title: "Thai Green Curry",
    description: "Fragrant coconut milk curry with crisp vegetables, Thai basil, and jasmine rice. Ready in 30 minutes.",
    image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=500&q=80",
    time: "30 min",
    prepTime: 30,
    calories: "480 kcal",
    servings: 4,
    rating: 4.7,
    badge: "🔥 Trending",
    category: "comfort",
    cuisine: "asian",
    diet: ["vegan", "vegetarian", "gluten-free", "dairy-free"],
    tags: ["Vegan", "Spicy"],
    difficulty: "medium"
  },
  {
    id: 8,
    title: "Shakshuka",
    description: "Eggs poached in a rich, spiced tomato and pepper sauce. The ultimate one-pan breakfast.",
    image: "https://images.unsplash.com/photo-1590412200988-a436970781fa?w=500&q=80",
    time: "25 min",
    prepTime: 25,
    calories: "310 kcal",
    servings: 2,
    rating: 4.8,
    badge: "⭐ Top Rated",
    category: "breakfast",
    cuisine: "middle-eastern",
    diet: ["vegetarian", "gluten-free"],
    tags: ["Vegetarian", "One-Pan"],
    difficulty: "easy"
  },
  {
    id: 9,
    title: "Beef Bulgogi Bowl",
    description: "Tender marinated Korean beef with sesame rice, pickled daikon, and a soft-boiled egg.",
    image: "https://images.unsplash.com/photo-1547592180-85f173990554?w=500&q=80",
    time: "40 min",
    prepTime: 40,
    calories: "560 kcal",
    servings: 2,
    rating: 4.8,
    badge: "⭐ Top Rated",
    category: "high-protein",
    cuisine: "asian",
    diet: ["dairy-free"],
    tags: ["High-Protein", "Korean"],
    difficulty: "medium"
  },
  {
    id: 10,
    title: "Margherita Flatbread",
    description: "Crispy flatbread with San Marzano tomatoes, fresh mozzarella, and torn basil. Done in 15 minutes.",
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=500&q=80",
    time: "15 min",
    prepTime: 15,
    calories: "390 kcal",
    servings: 2,
    rating: 4.5,
    badge: "⚡ Quick",
    category: "quick",
    cuisine: "italian",
    diet: ["vegetarian"],
    tags: ["Quick", "Vegetarian"],
    difficulty: "easy"
  },
  {
    id: 11,
    title: "Lemon Herb Salmon",
    description: "Pan-seared salmon fillet with a bright lemon-herb crust, served with roasted asparagus.",
    image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=500&q=80",
    time: "20 min",
    prepTime: 20,
    calories: "430 kcal",
    servings: 2,
    rating: 4.7,
    badge: "🔥 Trending",
    category: "high-protein",
    cuisine: "mediterranean",
    diet: ["gluten-free", "dairy-free"],
    tags: ["High-Protein", "Pescatarian"],
    difficulty: "easy"
  },
  {
    id: 12,
    title: "Churros with Chocolate Sauce",
    description: "Golden fried churros dusted in cinnamon sugar, served with a thick dark chocolate dipping sauce.",
    image: "https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=500&q=80",
    time: "35 min",
    prepTime: 35,
    calories: "490 kcal",
    servings: 4,
    rating: 4.6,
    badge: "👨‍🍳 Chef's Pick",
    category: "dessert",
    cuisine: "american",
    diet: ["vegetarian"],
    tags: ["Dessert", "Fried"],
    difficulty: "medium"
  },
  {
    id: 13,
    title: "Moroccan Chickpea Stew",
    description: "Warming spiced chickpea and sweet potato stew with harissa, preserved lemon, and fresh coriander.",
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=500&q=80",
    time: "45 min",
    prepTime: 45,
    calories: "380 kcal",
    servings: 4,
    rating: 4.6,
    badge: "🔥 Trending",
    category: "vegan",
    cuisine: "middle-eastern",
    diet: ["vegan", "vegetarian", "gluten-free", "dairy-free"],
    tags: ["Vegan", "High-Fibre"],
    difficulty: "easy"
  },
  {
    id: 14,
    title: "Chicken Tikka Masala",
    description: "Tender chicken in a velvety tomato-cream sauce with warming spices. A Friday night classic.",
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=500&q=80",
    time: "50 min",
    prepTime: 50,
    calories: "520 kcal",
    servings: 4,
    rating: 4.9,
    badge: "⭐ Top Rated",
    category: "comfort",
    cuisine: "indian",
    diet: ["gluten-free"],
    tags: ["High-Protein", "Spicy"],
    difficulty: "medium"
  },
  {
    id: 15,
    title: "Açaí Power Bowl",
    description: "Thick blended açaí base topped with granola, banana, fresh berries, honey, and coconut flakes.",
    image: "https://images.unsplash.com/photo-1590301157890-4810ed352733?w=500&q=80",
    time: "10 min",
    prepTime: 10,
    calories: "320 kcal",
    servings: 1,
    rating: 4.5,
    badge: "⚡ Quick",
    category: "breakfast",
    cuisine: "american",
    diet: ["vegan", "vegetarian", "gluten-free", "dairy-free"],
    tags: ["Vegan", "Quick"],
    difficulty: "easy"
  },
  {
    id: 16,
    title: "Beef Wellington",
    description: "Tenderloin wrapped in mushroom duxelles and golden puff pastry. The showstopper of all showstoppers.",
    image: "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=500&q=80",
    time: "120 min",
    prepTime: 120,
    calories: "780 kcal",
    servings: 6,
    rating: 4.9,
    badge: "👨‍🍳 Chef's Pick",
    category: "high-protein",
    cuisine: "french",
    diet: [],
    tags: ["High-Protein", "Special Occasion"],
    difficulty: "hard"
  },
  {
    id: 17,
    title: "Caprese Salad",
    description: "Thick slices of heirloom tomato, buffalo mozzarella, and fresh basil drizzled with aged balsamic.",
    image: "https://images.unsplash.com/photo-1608897013039-887f21d8c804?w=500&q=80",
    time: "10 min",
    prepTime: 10,
    calories: "240 kcal",
    servings: 2,
    rating: 4.4,
    badge: "⚡ Quick",
    category: "mediterranean",
    cuisine: "italian",
    diet: ["vegetarian", "gluten-free"],
    tags: ["Vegetarian", "No-Cook"],
    difficulty: "easy"
  },
  {
    id: 18,
    title: "Pad Thai",
    description: "Wok-fried rice noodles with prawns, egg, bean sprouts, and a tamarind-peanut sauce.",
    image: "https://images.unsplash.com/photo-1559314809-0d155014e29e?w=500&q=80",
    time: "25 min",
    prepTime: 25,
    calories: "510 kcal",
    servings: 2,
    rating: 4.7,
    badge: "🔥 Trending",
    category: "quick",
    cuisine: "asian",
    diet: ["gluten-free", "dairy-free"],
    tags: ["Quick", "Seafood"],
    difficulty: "medium"
  }
];
